---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "The Greeley Blended Learning Summit 2016"
keywords:    "Blended Learning, Summit, Personalized Learning, BL, PL"
description: ""
source_link: ""
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#197A9D'
  green:     '#93c47d'
  red:       '#DC5A3F'
  yellow:    '#ffd966'
  turquoise: '#76a5af'

kramdown:
  auto_ids:  false

